// Code generated by protoc-gen-gogo.
// source: any.proto
// DO NOT EDIT!

/*
Package anypb is a generated protocol buffer package.

It is generated from these files:
	any.proto

It has these top-level messages:
	Any
	AnyMap
*/
package anypb

import proto "github.com/gogo/protobuf/proto"
import math "math"

// discarding unused import gogoproto "github.com/gogo/protobuf/gogoproto/gogo.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type Any_Type int32

const (
	Any_NilType     Any_Type = 0
	Any_StringType  Any_Type = 1
	Any_UintType    Any_Type = 2
	Any_Uint32Type  Any_Type = 3
	Any_Uint64Type  Any_Type = 4
	Any_IntType     Any_Type = 5
	Any_Int32Type   Any_Type = 6
	Any_Int64Type   Any_Type = 7
	Any_Float32Type Any_Type = 8
	Any_Float64Type Any_Type = 9
	Any_BoolType    Any_Type = 10
	Any_ByteType    Any_Type = 11
	Any_TimeType    Any_Type = 30
)

var Any_Type_name = map[int32]string{
	0:  "NilType",
	1:  "StringType",
	2:  "UintType",
	3:  "Uint32Type",
	4:  "Uint64Type",
	5:  "IntType",
	6:  "Int32Type",
	7:  "Int64Type",
	8:  "Float32Type",
	9:  "Float64Type",
	10: "BoolType",
	11: "ByteType",
	30: "TimeType",
}
var Any_Type_value = map[string]int32{
	"NilType":     0,
	"StringType":  1,
	"UintType":    2,
	"Uint32Type":  3,
	"Uint64Type":  4,
	"IntType":     5,
	"Int32Type":   6,
	"Int64Type":   7,
	"Float32Type": 8,
	"Float64Type": 9,
	"BoolType":    10,
	"ByteType":    11,
	"TimeType":    30,
}

func (x Any_Type) Enum() *Any_Type {
	p := new(Any_Type)
	*p = x
	return p
}
func (x Any_Type) String() string {
	return proto.EnumName(Any_Type_name, int32(x))
}
func (x *Any_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Any_Type_value, data, "Any_Type")
	if err != nil {
		return err
	}
	*x = Any_Type(value)
	return nil
}

type AnyMap_Type int32

const (
	AnyMap_NilType           AnyMap_Type = 0
	AnyMap_AnyValueType      AnyMap_Type = 1
	AnyMap_AnyArrayType      AnyMap_Type = 2
	AnyMap_AnyStringMapType  AnyMap_Type = 3
	AnyMap_AnyUintMapType    AnyMap_Type = 4
	AnyMap_AnyUint32MapType  AnyMap_Type = 5
	AnyMap_AnyUint64MapType  AnyMap_Type = 6
	AnyMap_AnyIntMapType     AnyMap_Type = 7
	AnyMap_AnyInt32MapType   AnyMap_Type = 8
	AnyMap_AnyInt64MapType   AnyMap_Type = 9
	AnyMap_AnyFloat32MapType AnyMap_Type = 10
	AnyMap_AnyFloat64MapType AnyMap_Type = 11
	AnyMap_AnyBoolMapType    AnyMap_Type = 12
)

var AnyMap_Type_name = map[int32]string{
	0:  "NilType",
	1:  "AnyValueType",
	2:  "AnyArrayType",
	3:  "AnyStringMapType",
	4:  "AnyUintMapType",
	5:  "AnyUint32MapType",
	6:  "AnyUint64MapType",
	7:  "AnyIntMapType",
	8:  "AnyInt32MapType",
	9:  "AnyInt64MapType",
	10: "AnyFloat32MapType",
	11: "AnyFloat64MapType",
	12: "AnyBoolMapType",
}
var AnyMap_Type_value = map[string]int32{
	"NilType":           0,
	"AnyValueType":      1,
	"AnyArrayType":      2,
	"AnyStringMapType":  3,
	"AnyUintMapType":    4,
	"AnyUint32MapType":  5,
	"AnyUint64MapType":  6,
	"AnyIntMapType":     7,
	"AnyInt32MapType":   8,
	"AnyInt64MapType":   9,
	"AnyFloat32MapType": 10,
	"AnyFloat64MapType": 11,
	"AnyBoolMapType":    12,
}

func (x AnyMap_Type) Enum() *AnyMap_Type {
	p := new(AnyMap_Type)
	*p = x
	return p
}
func (x AnyMap_Type) String() string {
	return proto.EnumName(AnyMap_Type_name, int32(x))
}
func (x *AnyMap_Type) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AnyMap_Type_value, data, "AnyMap_Type")
	if err != nil {
		return err
	}
	*x = AnyMap_Type(value)
	return nil
}

type Any struct {
	Type             *Any_Type `protobuf:"varint,1,req,name=type,enum=anypb.Any_Type" json:"-"`
	StringValue      *string   `protobuf:"bytes,2,opt,name=string_value" json:"-"`
	Uint32Value      *uint32   `protobuf:"varint,3,opt,name=uint32_value" json:"-"`
	Uint64Value      *uint64   `protobuf:"varint,4,opt,name=uint64_value" json:"-"`
	Int32Value       *int32    `protobuf:"varint,5,opt,name=int32_value" json:"-"`
	Int64Value       *int64    `protobuf:"varint,6,opt,name=int64_value" json:"-"`
	Float32Value     *float32  `protobuf:"fixed32,7,opt,name=float32_value" json:"-"`
	Float64Value     *float64  `protobuf:"fixed64,8,opt,name=float64_value" json:"-"`
	BoolValue        *bool     `protobuf:"varint,9,opt,name=bool_value" json:"-"`
	ByteValue        []byte    `protobuf:"bytes,10,opt,name=byte_value" json:"-"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}

func (m *Any) GetType() Any_Type {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Any_NilType
}

func (m *Any) GetStringValue() string {
	if m != nil && m.StringValue != nil {
		return *m.StringValue
	}
	return ""
}

func (m *Any) GetUint32Value() uint32 {
	if m != nil && m.Uint32Value != nil {
		return *m.Uint32Value
	}
	return 0
}

func (m *Any) GetUint64Value() uint64 {
	if m != nil && m.Uint64Value != nil {
		return *m.Uint64Value
	}
	return 0
}

func (m *Any) GetInt32Value() int32 {
	if m != nil && m.Int32Value != nil {
		return *m.Int32Value
	}
	return 0
}

func (m *Any) GetInt64Value() int64 {
	if m != nil && m.Int64Value != nil {
		return *m.Int64Value
	}
	return 0
}

func (m *Any) GetFloat32Value() float32 {
	if m != nil && m.Float32Value != nil {
		return *m.Float32Value
	}
	return 0
}

func (m *Any) GetFloat64Value() float64 {
	if m != nil && m.Float64Value != nil {
		return *m.Float64Value
	}
	return 0
}

func (m *Any) GetBoolValue() bool {
	if m != nil && m.BoolValue != nil {
		return *m.BoolValue
	}
	return false
}

func (m *Any) GetByteValue() []byte {
	if m != nil {
		return m.ByteValue
	}
	return nil
}

type AnyMap struct {
	AnyType          *AnyMap_Type       `protobuf:"varint,1,req,name=any_type,enum=anypb.AnyMap_Type" json:"-"`
	AnyValue         *Any               `protobuf:"bytes,2,opt,name=any_value" json:"-"`
	AnyArray         []*AnyMap          `protobuf:"bytes,3,rep,name=any_array" json:"-"`
	AnyStringMap     map[string]*AnyMap `protobuf:"bytes,4,rep,name=any_string_map" json:"-" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnyUint32Map     map[uint32]*AnyMap `protobuf:"bytes,5,rep,name=any_uint32_map" json:"-" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnyUint64Map     map[uint64]*AnyMap `protobuf:"bytes,6,rep,name=any_uint64_map" json:"-" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnyInt32Map      map[int32]*AnyMap  `protobuf:"bytes,7,rep,name=any_int32_map" json:"-" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnyInt64Map      map[int64]*AnyMap  `protobuf:"bytes,8,rep,name=any_int64_map" json:"-" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	AnyBoolMap       map[bool]*AnyMap   `protobuf:"bytes,9,rep,name=any_bool_map" json:"-" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *AnyMap) Reset()         { *m = AnyMap{} }
func (m *AnyMap) String() string { return proto.CompactTextString(m) }
func (*AnyMap) ProtoMessage()    {}

func (m *AnyMap) GetAnyType() AnyMap_Type {
	if m != nil && m.AnyType != nil {
		return *m.AnyType
	}
	return AnyMap_NilType
}

func (m *AnyMap) GetAnyValue() *Any {
	if m != nil {
		return m.AnyValue
	}
	return nil
}

func (m *AnyMap) GetAnyArray() []*AnyMap {
	if m != nil {
		return m.AnyArray
	}
	return nil
}

func (m *AnyMap) GetAnyStringMap() map[string]*AnyMap {
	if m != nil {
		return m.AnyStringMap
	}
	return nil
}

func (m *AnyMap) GetAnyUint32Map() map[uint32]*AnyMap {
	if m != nil {
		return m.AnyUint32Map
	}
	return nil
}

func (m *AnyMap) GetAnyUint64Map() map[uint64]*AnyMap {
	if m != nil {
		return m.AnyUint64Map
	}
	return nil
}

func (m *AnyMap) GetAnyInt32Map() map[int32]*AnyMap {
	if m != nil {
		return m.AnyInt32Map
	}
	return nil
}

func (m *AnyMap) GetAnyInt64Map() map[int64]*AnyMap {
	if m != nil {
		return m.AnyInt64Map
	}
	return nil
}

func (m *AnyMap) GetAnyBoolMap() map[bool]*AnyMap {
	if m != nil {
		return m.AnyBoolMap
	}
	return nil
}

func init() {
	proto.RegisterEnum("anypb.Any_Type", Any_Type_name, Any_Type_value)
	proto.RegisterEnum("anypb.AnyMap_Type", AnyMap_Type_name, AnyMap_Type_value)
}
